version: "3.8"

services:
  webb-proj:
    build:
      context: .
      dockerfile: Dockerfile
    image: webb-proj:latest
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_HOST=db  # Использовать имя сервиса db в качестве хоста
      - DB_PORT=5432
      - DB_NAME=webbproj
      - DB_USER=postgres
      - DB_PASSWORD=123
      - DB_URL=jdbc:postgresql://db:5432/webbproj
    networks:
      - app_network
    restart: always

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=webbproj
    networks:
      - app_network
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always

networks:
  app_network:
    driver: bridge

volumes:
  db_data: