create table if not exists users
(
    id       bigint generated by default as identity primary key,
    username varchar(255) not null
        constraint username_unique unique,
    password varchar(255) not null
);

CREATE TABLE IF NOT EXISTS form
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    userId          BIGINT,
    fullName        VARCHAR(255) NOT NULL CHECK (fullName ~ '^[А-ЯЁ][а-яё]+(\s[А-ЯЁ][а-яё]+){1,2}$'),
    phone           VARCHAR(12)  NOT NULL CHECK (phone ~* '^((\+7|8)[0-9]{10})$')
        CONSTRAINT phone_unique UNIQUE,
    email           VARCHAR(255) NOT NULL CHECK (email ~*
                                                 '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$')
        CONSTRAINT email_unique UNIQUE,
    taskDescription VARCHAR(255),
    birthday DATE,
    gender VARCHAR(7),
    CONSTRAINT fk_user_id FOREIGN KEY (userId) REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS languages
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    language VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS form_languages
(
    form_id     BIGINT NOT NULL,
    language_id BIGINT NOT NULL,
    PRIMARY KEY (form_id, language_id),
    FOREIGN KEY (form_id) REFERENCES form (id) ON DELETE CASCADE,
    FOREIGN KEY (language_id) REFERENCES languages (id) ON DELETE CASCADE
);