create table if not exists users
(
    id       bigint generated by default as identity primary key,
    username varchar(255) not null
        constraint username_unique unique,
    password varchar(255) not null
);

CREATE TABLE IF NOT EXISTS form
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    userId          BIGINT,
    fullName        VARCHAR(255) NOT NULL CHECK (fullName ~ '^[А-ЯЁ][а-яё]+(\s[А-ЯЁ][а-яё]+){1,2}$'),
    phone           VARCHAR(12)  NOT NULL CHECK (phone ~* '^((\+7|8)[0-9]{10})$')
        CONSTRAINT phone_unique UNIQUE,
    email           VARCHAR(255) NOT NULL CHECK (email ~*
                                                 '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$')
        CONSTRAINT email_unique UNIQUE,
    taskDescription VARCHAR(255),
    CONSTRAINT fk_user_id FOREIGN KEY (userId) REFERENCES users (id)
);