create table if not exists admins
(
    id       bigint generated by default as identity primary key,
    username varchar(255) not null
        constraint admin_username_unique unique,
    password varchar(255) not null
);

insert into admins values (1, 'admin1', 'pmWkWSBCL51Bfkhn79xPuKBKHz//H6B+mY6G9/eieuM=');
-- 123